times = ('FLAMENGO','PALMEIRAS','BOTAFOGO','BAHIA','ATHLETICO-PR','SÃO PAULO','CRUZEIRO','FORTALEZA','RED BULL BRAGANTINO','INTERNACIONAL','ATLÉTICO-MG','JUVENTUDE','CRICIÚMA','CUIABÁ','VITÓRIA','VASCO','ATLÉTICO-GO','GRÊMIO','CORINTHIANS','FLUMINENSE')
print('---' * 6)
print('Lista de times do Brasileirão')
print(times)
print('-=-' * 6)
print('Os 5 primeiros são:')
print(times[0:5])
print('¬|¬' * 6)
print('Os últimos 4 são:')
print(times[16:])
print('*¨*' * 6)
print('Em ordem Alfabética:')
print(sorted(times))
print('%+%' * 6)
print('Com o time fortaleza estando na posição {}'.format(times.index('FORTALEZA')))
